# Generated by Django 6.0.2 on 2026-02-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonymizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbuseFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("high_traffic", "High Traffic"),
                            ("rapid_creation", "Rapid Creation"),
                            ("suspicious_ip", "Suspicious IP"),
                            ("manual", "Manual Flag"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("action_taken", models.TextField(blank=True, default="")),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abuse_flags",
                        to="anonymizer.anonymousrepo",
                    ),
                ),
            ],
            options={
                "ordering": ["-flagged_at"],
            },
        ),
    ]
