# Generated by Django 6.0.2 on 2026-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonymizer", "0002_abuseflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousrepo",
            name="allow_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="anonymousrepo",
            name="allowed_configs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anonymousrepo",
            name="allowed_splits",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anonymousrepo",
            name="preview_rows",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
