# Generated by Django 6.0.2 on 2026-02-10 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anonymizer", "0003_add_download_and_preview_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymousrepo",
            name="allowed_configs",
        ),
        migrations.RemoveField(
            model_name="anonymousrepo",
            name="allowed_splits",
        ),
        migrations.RemoveField(
            model_name="anonymousrepo",
            name="preview_rows",
        ),
    ]
