# Generated by Django 6.0.2 on 2026-02-11 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anonymizer", "0004_remove_preview_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="user_agent",
        ),
    ]
