# Generated by Django 6.0.2 on 2026-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0006_activitylog_actor_type_anonymousrepo_colab_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('extended', 'Extended'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=20),
        ),
    ]
