# Generated by Django 6.0.2 on 2026-02-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0009_alter_activitylog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbuseFlag',
        ),
    ]
