# Generated by Django 6.0.2 on 2026-02-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0010_remove_abuseflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousrepo',
            name='allow_download',
        ),
    ]
