# Generated by Django 6.0.2 on 2026-07-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0011_remove_allow_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousrepo',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='anonymousrepo',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='actor_type',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('owner', 'Owner')], default='viewer', max_length=10),
        ),
    ]
