# Generated by Django 6.0.2 on 2026-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hf_api_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
